def Count_Freq_Nuc(seq):
  FreqDict = {
      'A': 0,
      'C': 0,
      'G': 0,
      'T': 0
  }

  for nucleotide in seq:
    FreqDict[nucleotide] += 1 # count 

  return FreqDict


Seq = 'GTTGTCCCCGCGTGTGTTTAAGAGGGAAACACAGCACCTGTCCCGATCGCTTCGATTAATCGAAATATCAAGAAGCCTGAACCATACTGACGATCCCAGCTTAGACCTAGAAACAATGGCGTCGGGTATGCCGGTGCCCATTAATACGCAGTTACGTTCTGGGTCCAAGTACAGAGCTCCCTTTTTTGGATATGTGACACCTAGTGGCCGCGATCTCAGTAAGCAGCAGATTAGGACGAGACCCTCCATGCGTATGCACCGTCGCTGAGCGCACTTGCGGCCGGGGATGCCAGATCGCCAAAGGGACTCTCACTAGGCGGCGTCTTGGGCGTGCCATATGCTGAGAATCGTCGTTCTGGTCTATATAATAGCAAAGGAAATGACATTTCGTCTGGCATTGTTAAGGGTAGAGGAGGGGGGTACGGCTGTATCAAGATAAACTCGGTGAAAGTTTATAGAATACGTCGTCGCTCCCTGGAGAGATCGTGTGGGCAATCGCCCCAATAAATGAGGGGATTCTGTGATGGCAGTCCAAACATCGGAAGAGGGAGACCACATAGTCCTAAACACGATATCTAAAGTGCTTACGTAGTTCGGTTGGGGTGAAGTATAACGAACGCGTCCCGGGTGAGCGCTCATGCAGACCCGCAATATTTTAATCCGGAGAGCGGTCAGCTGTTTGTAAATGACGTCTTGTAACACCTCCGGCCGAGCATGACCGAACAGAGTAAACTCACGTGAGCGCACGGTTTGGCGGAGTGCCCGTTGTAATTCACTGACATATTTTAGGCACGAAACTATTCAAAATTCAATCGATCTTTGAATAATCAGGTCGTTGAGAATAAATTAGCGCTCGTTATGGCTTT'
Freq_Seq = Count_Freq_Nuc(Seq)
print(' '.join([str(value) for key, value in Freq_Seq.items()]))